[project]
name = "learn-langchain"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain>=1.0.3",
]

[tool.uv.workspace]
members = [
    "scenarios/chatbot/simple-chatbot",
]
